services:
  - type: web
    name: counter24
    runtime: node
    plan: starter
    buildCommand: NPM_CONFIG_PRODUCTION=false npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: NODE_ENV
        value: production
